CREATE TABLE event_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NULL,
  actor_type ENUM('management','mobile','audit','payment','anonymous','system') NOT NULL DEFAULT 'anonymous',
  actor_id BIGINT UNSIGNED NULL,
  actor_role VARCHAR(40) NULL,
  channel VARCHAR(40) NOT NULL,
  action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(120) NULL,
  entity_id VARCHAR(80) NULL,
  method VARCHAR(10) NOT NULL,
  path VARCHAR(500) NOT NULL,
  route_path VARCHAR(500) NULL,
  status_code SMALLINT UNSIGNED NOT NULL,
  success TINYINT(1) NOT NULL DEFAULT 0,
  ip_address VARCHAR(80) NULL,
  user_agent VARCHAR(500) NULL,
  request_json JSON NULL,
  response_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_event_logs_org_created (organization_id, created_at),
  KEY idx_event_logs_actor_created (actor_type, actor_id, created_at),
  KEY idx_event_logs_entity_created (entity_type, entity_id, created_at),
  KEY idx_event_logs_action_created (action, created_at),
  CONSTRAINT fk_event_logs_org FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
