CREATE TABLE booking_edit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  market_id BIGINT UNSIGNED NOT NULL,
  booking_id BIGINT UNSIGNED NOT NULL,
  booking_item_id BIGINT UNSIGNED NOT NULL,
  old_booth_id BIGINT UNSIGNED NOT NULL,
  new_booth_id BIGINT UNSIGNED NOT NULL,
  old_booking_date DATE NOT NULL,
  new_booking_date DATE NOT NULL,
  old_unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  new_unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  edited_by_admin_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_booking_edit_logs_org_market_created (organization_id, market_id, created_at),
  KEY idx_booking_edit_logs_booking (booking_id, booking_item_id),
  CONSTRAINT fk_booking_edit_logs_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_booking_edit_logs_market FOREIGN KEY (market_id) REFERENCES markets(id),
  CONSTRAINT fk_booking_edit_logs_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  CONSTRAINT fk_booking_edit_logs_item FOREIGN KEY (booking_item_id) REFERENCES booking_items(id),
  CONSTRAINT fk_booking_edit_logs_old_booth FOREIGN KEY (old_booth_id) REFERENCES booths(id),
  CONSTRAINT fk_booking_edit_logs_new_booth FOREIGN KEY (new_booth_id) REFERENCES booths(id),
  CONSTRAINT fk_booking_edit_logs_admin FOREIGN KEY (edited_by_admin_id) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
