CREATE TABLE accounting_document_sequences (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  document_type ENUM('receipt','tax_invoice','credit_note') NOT NULL,
  period_ym CHAR(6) NOT NULL,
  sequence_no INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_accounting_document_sequence (organization_id, document_type, period_ym),
  CONSTRAINT fk_accounting_document_sequences_org FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE accounting_documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  document_type ENUM('receipt','tax_invoice','credit_note') NOT NULL,
  document_no VARCHAR(40) NOT NULL,
  document_status ENUM('issued','cancelled','void') NOT NULL DEFAULT 'issued',
  payment_id BIGINT UNSIGNED NULL,
  booking_id BIGINT UNSIGNED NULL,
  audit_check_id BIGINT UNSIGNED NULL,
  source_document_id BIGINT UNSIGNED NULL,
  issue_date DATE NOT NULL,
  subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  vat_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  withholding_tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  customer_name VARCHAR(255) NULL,
  organization_snapshot_json JSON NULL,
  customer_snapshot_json JSON NULL,
  line_items_json JSON NULL,
  issued_by_admin_id BIGINT UNSIGNED NULL,
  cancelled_by_admin_id BIGINT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancel_reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_accounting_documents_org_no (organization_id, document_no),
  KEY idx_accounting_documents_payment (organization_id, payment_id),
  KEY idx_accounting_documents_booking (organization_id, booking_id),
  KEY idx_accounting_documents_status (organization_id, document_type, document_status, issue_date),
  CONSTRAINT fk_accounting_documents_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_accounting_documents_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
  CONSTRAINT fk_accounting_documents_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
  CONSTRAINT fk_accounting_documents_audit_check FOREIGN KEY (audit_check_id) REFERENCES audit_checks(id),
  CONSTRAINT fk_accounting_documents_source FOREIGN KEY (source_document_id) REFERENCES accounting_documents(id),
  CONSTRAINT fk_accounting_documents_issued_by FOREIGN KEY (issued_by_admin_id) REFERENCES admin_users(id),
  CONSTRAINT fk_accounting_documents_cancelled_by FOREIGN KEY (cancelled_by_admin_id) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
