CREATE TABLE subscription_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  trial_days INT NOT NULL DEFAULT 30,
  billing_interval ENUM('monthly','yearly','custom') NOT NULL DEFAULT 'monthly',
  billing_interval_count INT NOT NULL DEFAULT 1,
  currency_code CHAR(3) NOT NULL DEFAULT 'THB',
  base_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  setup_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  included_markets INT NOT NULL DEFAULT 1,
  included_admin_users INT NOT NULL DEFAULT 1,
  included_active_booths INT NOT NULL DEFAULT 0,
  included_monthly_bookings INT NOT NULL DEFAULT 0,
  overage_market_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  overage_admin_user_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  overage_booth_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  overage_booking_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  vat_applicable TINYINT(1) NOT NULL DEFAULT 1,
  features_json JSON NULL,
  status ENUM('active','inactive','legacy') NOT NULL DEFAULT 'active',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_subscription_plans_code (code),
  KEY idx_subscription_plans_status (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_signup_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_no VARCHAR(40) NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  company_email_enc TEXT NOT NULL,
  company_email_hash CHAR(64) NOT NULL,
  company_phone_enc TEXT NOT NULL,
  company_phone_hash CHAR(64) NOT NULL,
  line_id_enc TEXT NULL,
  address_enc TEXT NULL,
  supervisor_name_enc TEXT NOT NULL,
  supervisor_email_enc TEXT NOT NULL,
  supervisor_email_hash CHAR(64) NOT NULL,
  supervisor_phone_enc TEXT NULL,
  supervisor_phone_hash CHAR(64) NULL,
  supervisor_password_hash VARCHAR(255) NOT NULL,
  market_count_estimate INT NOT NULL DEFAULT 1,
  expected_go_live_date DATE NULL,
  preferred_plan_id BIGINT UNSIGNED NULL,
  preferred_billing_interval ENUM('monthly','yearly') NOT NULL DEFAULT 'yearly',
  notes TEXT NULL,
  status ENUM('pending_review','contacted','approved','rejected','cancelled','provisioned') NOT NULL DEFAULT 'pending_review',
  source VARCHAR(60) NOT NULL DEFAULT 'landing',
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  metadata_json JSON NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_organization_signup_requests_request_no (request_no),
  KEY idx_organization_signup_requests_status (status, created_at),
  KEY idx_organization_signup_requests_company_email (company_email_hash),
  KEY idx_organization_signup_requests_supervisor_email (supervisor_email_hash),
  CONSTRAINT fk_organization_signup_requests_plan FOREIGN KEY (preferred_plan_id) REFERENCES subscription_plans(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_subscriptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  subscription_code VARCHAR(40) NOT NULL,
  organization_id BIGINT UNSIGNED NULL,
  signup_request_id BIGINT UNSIGNED NULL,
  plan_id BIGINT UNSIGNED NOT NULL,
  status ENUM('pending_activation','trialing','active','past_due','suspended','cancelled','expired') NOT NULL DEFAULT 'pending_activation',
  billing_currency CHAR(3) NOT NULL DEFAULT 'THB',
  billing_interval ENUM('monthly','yearly','custom') NOT NULL DEFAULT 'yearly',
  billing_interval_count INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  setup_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  vat_rate DECIMAL(5,2) NOT NULL DEFAULT 7.00,
  subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  vat_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  included_markets INT NOT NULL DEFAULT 1,
  included_admin_users INT NOT NULL DEFAULT 1,
  included_active_booths INT NOT NULL DEFAULT 0,
  included_monthly_bookings INT NOT NULL DEFAULT 0,
  trial_starts_at DATETIME NULL,
  trial_ends_at DATETIME NULL,
  current_period_start DATETIME NULL,
  current_period_end DATETIME NULL,
  next_billing_at DATETIME NULL,
  activated_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  last_invoiced_at DATETIME NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_organization_subscriptions_code (subscription_code),
  KEY idx_organization_subscriptions_org_status (organization_id, status),
  KEY idx_organization_subscriptions_signup_status (signup_request_id, status),
  CONSTRAINT fk_organization_subscriptions_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_organization_subscriptions_signup FOREIGN KEY (signup_request_id) REFERENCES organization_signup_requests(id),
  CONSTRAINT fk_organization_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_subscription_usages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_subscription_id BIGINT UNSIGNED NOT NULL,
  metric_code ENUM('markets','admin_users','active_booths','monthly_bookings','api_calls') NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  included_quantity INT NOT NULL DEFAULT 0,
  actual_quantity INT NOT NULL DEFAULT 0,
  billable_quantity INT NOT NULL DEFAULT 0,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  snapshot_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_organization_subscription_usages_period (organization_subscription_id, metric_code, period_start, period_end),
  KEY idx_organization_subscription_usages_metric (metric_code, period_start),
  CONSTRAINT fk_organization_subscription_usages_subscription FOREIGN KEY (organization_subscription_id) REFERENCES organization_subscriptions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE subscription_invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_subscription_id BIGINT UNSIGNED NOT NULL,
  invoice_no VARCHAR(40) NOT NULL,
  invoice_type ENUM('subscription','setup','overage','adjustment') NOT NULL DEFAULT 'subscription',
  status ENUM('draft','issued','paid','void','overdue','cancelled') NOT NULL DEFAULT 'draft',
  currency_code CHAR(3) NOT NULL DEFAULT 'THB',
  subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  vat_rate DECIMAL(5,2) NOT NULL DEFAULT 7.00,
  vat_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  issued_at DATETIME NULL,
  due_at DATETIME NULL,
  paid_at DATETIME NULL,
  period_start DATE NULL,
  period_end DATE NULL,
  reference_note TEXT NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_subscription_invoices_no (invoice_no),
  KEY idx_subscription_invoices_subscription_status (organization_subscription_id, status, due_at),
  CONSTRAINT fk_subscription_invoices_subscription FOREIGN KEY (organization_subscription_id) REFERENCES organization_subscriptions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE subscription_invoice_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  subscription_invoice_id BIGINT UNSIGNED NOT NULL,
  item_type ENUM('plan_fee','setup_fee','market_overage','admin_overage','booth_overage','booking_overage','adjustment') NOT NULL,
  metric_code VARCHAR(50) NULL,
  description VARCHAR(255) NOT NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  metadata_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_subscription_invoice_items_invoice (subscription_invoice_id),
  CONSTRAINT fk_subscription_invoice_items_invoice FOREIGN KEY (subscription_invoice_id) REFERENCES subscription_invoices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO subscription_plans (
  code, name, description, trial_days, billing_interval, billing_interval_count, currency_code,
  base_price, setup_fee, included_markets, included_admin_users, included_active_booths,
  included_monthly_bookings, overage_market_price, overage_admin_user_price, overage_booth_price,
  overage_booking_price, vat_applicable, features_json, status, sort_order
) VALUES
(
  'starter',
  'Starter',
  'เหมาะสำหรับตลาดเดี่ยวที่เริ่มต้นใช้งานระบบจองพื้นที่ขาย',
  365,
  'yearly',
  1,
  'THB',
  12000.00,
  0.00,
  1,
  3,
  80,
  500,
  2500.00,
  500.00,
  15.00,
  20.00,
  1,
  JSON_ARRAY('1 market', '3 admin users', 'vendor booking app', 'accounting reports'),
  'active',
  1
),
(
  'growth',
  'Growth',
  'เหมาะสำหรับองค์กรที่มีหลายตลาดและต้องการทีมงานหลายสิทธิ์',
  365,
  'yearly',
  1,
  'THB',
  28000.00,
  0.00,
  3,
  10,
  300,
  3000,
  2000.00,
  350.00,
  10.00,
  15.00,
  1,
  JSON_ARRAY('3 markets', '10 admin users', 'advanced reports', 'audit workflow'),
  'active',
  2
),
(
  'enterprise',
  'Enterprise',
  'เหมาะสำหรับองค์กรขนาดใหญ่ที่ต้องการปรับแต่งตามรูปแบบธุรกิจ',
  365,
  'yearly',
  1,
  'THB',
  0.00,
  0.00,
  9999,
  9999,
  9999,
  999999,
  0.00,
  0.00,
  0.00,
  0.00,
  1,
  JSON_ARRAY('custom onboarding', 'dedicated support', 'custom billing rules', 'integration-ready'),
  'active',
  3
);
