CREATE TABLE IF NOT EXISTS public_user_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id VARCHAR(40) NOT NULL,
  display_name_enc TEXT NULL,
  email_enc TEXT NOT NULL,
  email_hash CHAR(64) NOT NULL,
  phone_enc TEXT NULL,
  phone_hash CHAR(64) NULL,
  phone_verified_at DATETIME NULL,
  firebase_uid VARCHAR(191) NULL,
  password_hash VARCHAR(255) NULL,
  avatar_url VARCHAR(1024) NULL,
  address_enc TEXT NULL,
  province_id INT UNSIGNED NULL,
  amphure_id INT UNSIGNED NULL,
  subdistrict_id INT UNSIGNED NULL,
  pdpa_terms_accepted_at DATETIME NULL,
  pdpa_marketing_accepted_at DATETIME NULL,
  notification_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_public_user_profiles_public_id (public_id),
  UNIQUE KEY uq_public_user_profiles_email_hash (email_hash),
  UNIQUE KEY uq_public_user_profiles_firebase_uid (firebase_uid),
  KEY idx_public_user_profiles_phone_hash (phone_hash),
  KEY idx_public_user_profiles_location (province_id, amphure_id, subdistrict_id),
  CONSTRAINT fk_public_user_profiles_province FOREIGN KEY (province_id) REFERENCES master_provinces(id),
  CONSTRAINT fk_public_user_profiles_amphure FOREIGN KEY (amphure_id) REFERENCES master_amphures(id),
  CONSTRAINT fk_public_user_profiles_subdistrict FOREIGN KEY (subdistrict_id) REFERENCES master_districts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
